### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by tfleige**
Add dual license model (LGPLv3 and ASLv2)

### CODE REVIEW

**Comment by tfleige** [comment]
change to dual license model

**Comment by wolfc** [comment]
The commits from #3 and #4 need to be combined in this single PR.

**Comment by tfleige** [comment]
Since the source files contain each a LGPL v2.1 header, a dual license with LGPL 3.0 and LGPL 2.1 makes more sense.

**Comment by tfleige** [comment]
Closing pull request in order to change to LGPLv2.1

**Pull request closed without merging**
