### PR TITLE
[WFLY-11622] Change DeliveryGroup annotation so that now it can suppo…

### PR DESCRIPTION
**Pull request by fl4via**
…rt multiple delivery groups

Jira: https://issues.jboss.org/browse/WFLY-11622

EAP Jira: https://issues.jboss.org/browse/EAP7-720

Analysis document: https://github.com/wildfly/wildfly-proposals/pull/172

### CODE REVIEW

**Comment by fl4via** [comment]
@bstansberry are you the one responsible for reviewing these PRs, or do you know who should review? This is a blocker for a REF that should get into Wildfly branch. Thanks!

**Comment by fl4via** [comment]
@dmlloyd wdym? Isn't the change I'm doing making it multi valued? Or do you mean repeatable, i.e., multiple annotations for the same class?
And why is this incompatible? Isn't @DeliveryGroup("delivery-group") going to still compile after this change?

**Comment by dmlloyd** [comment]
It's source compatible but binary incompatible because the method signature is changing, which will cause code which was compiled against the previous version to fail.

Making it repeatable doesn't change the signature of the existing method though; instead it adds a new type that we can easily check for.  Thus that would be a source *and* binary compatible change.

**Comment by fl4via** [comment]
@dmlloyd done. There is only one pending issue. This requires jdk8. I hope that this is not an issue.
Also, because of that, Idea is complaining that jdk8 is required, it marks the annotation with compilation error, and fixing that in Idea causes the following addition to the pom.xml:
<build>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
               <source>8</source>
               <target>8</target>
            </configuration>
         </plugin>
      </plugins>
   </build>
However, without that, the project builds normally for me. I decided to check to you what is the procedure in this case, so I haven't added the pom to the PR yet. Wdyt?

**Comment by bstansberry** [comment]
@fl4via Perhaps we can just create a 2.1.x branch from the 2.1.0.Final tag. In the remote chance there needs to be a fix from this repo for an EAP 6.4 CP then that branch would be sitting there ready to go. The possibility of needing a 2.1.x is the only impediment I can think of to changing the pom to require JDK 8.

**Comment by fl4via** [comment]
@bstansberry okay, I'll add the change to the pom then, and you and/or @dmlloyd  can create the branch. Thanks for the feedback!

**Comment by fl4via** [comment]
@bstansberry / @dmlloyd done, ready for review again

**Pull request merged**
